project_id             = "gke-workload-1"
region                 = "us-central1"
zone                   = "us-central1-a"
machine_type           = "f1-micro"
instance_name          = "terraform-instance"